version: '3'

services:
  app:
    build: .
    entrypoint: npm run start:docker
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - redis

  crm:
    build: .
    entrypoint: npm run mock:api
    ports:
      - 8000:8000
    volumes:
      - .:/home/node/app

  redis:
    image: redis:7.0.8-alpine
    ports:
      - '6379:6379'
